### ISSUE TITLE
How to connect the hand-e to the robot for MoveIt2/ROS2 usage ?

### ISSUE THREAD

**Issue by Gredin67** [mcboyd/ur5e_with_robotiq_hande#1]
Hi, I want to control a UR5e with a Hand-e (with camera) from MoveIt2/ROS2.
Is there a driver for the Hand-E already available ?
How do you manage to control your hardware setup ?

**Comment by mcboyd** [comment]
Hi. I have not seen a ROS2 driver for the Hand-E yet. I started with this ROS1 version to get everything working. My next step is to port this over to ROS2 and MoveIt2 (though that probably won't happen until June or July). 
To control the gripper, I run the action server in this fork: https://github.com/mcboyd/robotiq.  
Basic steps (all ROS1):
 - Start UR driver w/ tool communication enabled
 - Start "external control" URCap on teach pendant
 - Launch action server from above repo: `roslaunch robotiq_2f_gripper_control ur5e_hande_action_server.launch` 
 - Run action client to send commands to gripper: `rosrun robotiq_2f_gripper_control robotiq_2f_action_client_example.py`

**Comment by Gredin67** [comment]
Thanks for the hints. Do you think it should work on Noetic too (I only have a Ubuntu 20 available at the moment ? Do you know a MoveIt tutorial (or MoveIt Task Constructor) that could work with the hand ? Or be slightly adapted for a Demo ?

**Comment by Gredin67** [comment]
building a workspace with your project in Noetic (git clone https://github.com/mcboyd/robotiq and https://github.com/mcboyd/ur5e_with_robotiq_hande), I just had to install `ros-noetic-soem` manually.
But running `roslaunch robotiq_2f_gripper_control ur5e_hande_action_server.launch`
gives me `ModuleNotFoundError: No module named 'robotiq_2f_gripper'`

**Comment by mcboyd** [comment]
Hi. I have not tested it on Noetic, but it's close enough to Melodic that I suspect it _should_ work. 
I have not looked at any of the MoveIt tutorials to see what may work with the hand, unfortunately, so I cannot provide much guidance there. That said, once the URDF/SRDF are available to MoveIt, the planning is not much different from any arm+gripper combo. You would just have to pipe the gripper commands to the Hand-E action server indicated above. 

Regarding the `ModuleNotFoundError`, are you able to `catkin_make` my fork of the Robotiq packages successfully? The module in question is located here: `robotiq/robotiq_2f_gripper_control/src/robotiq_2f_gripper_control/`, so if it builds successfully, it should be able to find it. Are there any errors during the make process? Did you source `devel/setup.bash` after the make process?

**Comment by Gredin67** [comment]
I did `catkin_make` in a new workspace with only `robotiq`, `ur5e_hande_moveit_config` and `ur5e_with_robotiq_hande` repos, no error in make process, I did `devel/setup.bash`.  Can you give me a hint where the module is supposed to be installed ? 
I tried to tweak the cmake config to get robotiq_2f_gripper.py Module installed properly without success. 
Any idea what could be the make issue ?
